using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NameTagSyncModel
{
    [RealtimeProperty(1, true, true)]
    private bool _isTeacher;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NameTagSyncModel : RealtimeModel {
    public bool isTeacher {
        get {
            return _isTeacherProperty.value;
        }
        set {
            if (_isTeacherProperty.value == value) return;
            _isTeacherProperty.value = value;
            InvalidateReliableLength();
            FireIsTeacherDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(NameTagSyncModel model, T value);
    public event PropertyChangedHandler<bool> isTeacherDidChange;
    
    public enum PropertyID : uint {
        IsTeacher = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _isTeacherProperty;
    
    #endregion
    
    public NameTagSyncModel() : base(null) {
        _isTeacherProperty = new ReliableProperty<bool>(1, _isTeacher);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _isTeacherProperty.UnsubscribeCallback();
    }
    
    private void FireIsTeacherDidChange(bool value) {
        try {
            isTeacherDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _isTeacherProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _isTeacherProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.IsTeacher: {
                    changed = _isTeacherProperty.Read(stream, context);
                    if (changed) FireIsTeacherDidChange(isTeacher);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _isTeacher = isTeacher;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
